apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: local-cluster-preflight
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.19.0"
              message: "Kubernetes version is too old"
          - pass:
              message: "Kubernetes version is supported"
    - nodeResources:
        checkName: "Node Resources"
        outcomes:
          - fail:
              when: "count() < 1"
              message: "Must have at least 1 node"
          - warn:
              when: "min(memoryCapacity) < 4Gi"
              message: "Nodes should have at least 4GB memory"
          - pass:
              message: "Node resources are adequate"
    - storageClass:
        checkName: "Default Storage Class"
        storageClassName: ""
        outcomes:
          - fail:
              message: "No default storage class found"
          - pass:
              message: "Default storage class is available"
