apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: redactor-demo
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - data:
        name: sensitive-data-example
        data: |
          # Example configuration with sensitive data
          database:
            host: db.example.com
            username: admin
            password: super_secret_password_123
            connection_string: "postgresql://admin:super_secret_password_123@db.example.com:5432/myapp"
          
          api:
            api_key: demo_key_1234567890abcdef1234567890abcdef
            api-token: token_abcdef1234567890
            secret_key: "very-secret-key-here"
            
          server:
            ip_address: 192.168.1.100
            hostname: my-secret-server.internal.com
            
          user_data:
            email: user@company.com
            social_security: 123-45-6789
  analyzers:
    - clusterVersion:
        outcomes:
          - pass:
              message: "Kubernetes version is OK"
  redactors:
    - name: "Password Redactor"
      removals:
        regex:
          - pattern: '(password\s*[:=]\s*)([^\s\n]+)'
            replacement: '${1}***REDACTED***'
    - name: "API Key Redactor"
      removals:
        regex:
          - pattern: '(api[_-]?key\s*[:=]\s*)([^\s\n]+)'
            replacement: '${1}***REDACTED***'
          - pattern: '(api[_-]?token\s*[:=]\s*)([^\s\n]+)'
            replacement: '${1}***REDACTED***'
          - pattern: '(secret[_-]?key\s*[:=]\s*)([^\s\n"]+)'
            replacement: '${1}***REDACTED***'
    - name: "Connection String Redactor"
      removals:
        regex:
          - pattern: '(postgresql://[^:]+:)([^@]+)(@)'
            replacement: '${1}***REDACTED***${3}'
    - name: "IP Address Redactor"
      removals:
        regex:
          - pattern: '\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b'
            replacement: '***REDACTED_IP***'
    - name: "Email Redactor"
      removals:
        regex:
          - pattern: '\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
            replacement: '***REDACTED_EMAIL***'
    - name: "SSN Redactor"
      removals:
        regex:
          - pattern: '\b\d{3}-\d{2}-\d{4}\b'
            replacement: '***REDACTED_SSN***'
